version: "3.8"

services:
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
      REPLACE_ENV_VARIABLES: "true"
    ports:
      - "25565:25577"
    volumes:
      - ./docker-compose/bungeecord/settings/config.yml:/config.yml
      - ./docker-compose/bungeecord/settings/BungeeUtilisalsX.jar:/plugins/BungeeUtilisalsX.jar
      - ./docker-compose/bungeecord/files:/server
  velocity:
    image: itzg/bungeecord
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    ports:
      - "25566:25577"
    volumes:
      - ./docker-compose/velocity/settings/velocity.toml:/velocity.toml
      - ./docker-compose/velocity/settings/BungeeUtilisalsX.jar:/plugins/BungeeUtilisalsX.jar
      - ./docker-compose/velocity/files:/server
  paper-1:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25570:25565"
    environment:
      TYPE: PAPER
      EULA: "TRUE"
    volumes:
      - ./docker-compose/paper-1/files:/data