name: Java CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: 'maven'
      - name: Run tests with maven
        run: mvn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: 'maven'
      - name: Build with Maven
        run: mvn package
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: BungeeUtilisalsX
          retention-days: 14
          path: |
            bungee/target/BungeeUtilisalsX*.jar
            velocity/target/BungeeUtilisalsX*.jar
            webapi/target/BungeeUtilisalsX*.jar

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Download math result for job 1
#        uses: actions/download-artifact@v2
#        with:
#          name: BungeeUtilisalsX
#      - # TODO: send to dieterblancke.xyz