# Enable to get debug messages (where they are enabled)
debug: false

# How long should items be cached? (in minutes)
cache-duration-minutes: 10

# Should IP's be exposed or not? If you expose these, please ENABLE authentication!!!
expose-ips: false

# Should authentication be enabled or not (through API keys)
auth-enabled: true

storage:
  # Possible storage types: MYSQL, POSTGRESQL, MARIADB & MONGODB | MySQL recommended
  #
  # It's recommended to use MYSQL, POSTGRESQL or MARIADB for storage.
  type: 'MYSQL'

  # The hostname (IP) to connect to
  hostname: '127.0.0.1'
  # Default ports:
  # MySQL / MariaDB: 3306, PostgreSQL: 5432, MongoDB: 27017
  port: 3306
  # The database / scheme name
  database: 'database'
  # The username, should at least have write & read access to the database above!
  username: 'username'
  # The password corresponding to the username above
  password: 'password'

  # Custom properties to be added to the connection uri
  properties:
    serverTimezone: 'Europe/Brussels'
    characterEncoding: utf8
    useSSL: true

  pool:
    # How many connections are allowed to be made?
    # Find more information at:
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    max-pool-size: 5
    # How many idle connections should be maintained?
    min-idle: 3
    # If more connections than min-idle are opened, after how many seconds should one of those connections be closed?
    idle-timeout: 30
    # Maximum lifetime of a connection. Time in seconds.
    max-lifetime: 300
    # How long should BungeeUtilisalsX wait before timing out a connection?
    connection-timeout: 8